---
- name: Run Lenovo Redfish Firmware Check
  hosts: XCC01
  connection: local
  gather_facts: false
  vars:
    bmc_ip: 192.168.0.222
    ansible_user: pptadmin

  tasks:
    - name: Run Lenovo firmware inventory script
      ansible.builtin.command: >
        python3 script/get_system_inventory.py
        -i {{ bmc_ip }}
        -u {{ ansible_user }}
        -p {{ ansible_password }}
      register: result

    - name: Show output
      ansible.builtin.debug:
        var: result.stdout
